"""create updated_at triggers

Revision ID: 1ad18a6a01e4
Revises: 8baabb41920c
Create Date: 2024-05-19 01:21:22.377882

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ad18a6a01e4"
down_revision: Union[str, None] = "8baabb41920c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """CREATE OR REPLACE FUNCTION set_updated_at()
            RETURNS TRIGGER 
            LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                NEW.updated_at := TIMEZONE('UTC', NOW());
                RETURN NEW;
            END;
            $$;"""
    )

    op.execute(
        """CREATE TRIGGER set_updated_at_for_resource_trigger
			BEFORE UPDATE ON "resource"
			FOR EACH ROW
			EXECUTE FUNCTION set_updated_at();"""
    )

    op.execute(
        """CREATE TRIGGER set_updated_at_for_cart_trigger
			BEFORE UPDATE ON "cart"
			FOR EACH ROW
			EXECUTE FUNCTION set_updated_at();"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER set_updated_at_for_resource_trigger ON "resource";""")
    op.execute("""DROP TRIGGER set_updated_at_for_cart_trigger ON "cart";""")
    # ### end Alembic commands ###
