"""create tables

Revision ID: 55d481cd682c
Revises: 
Create Date: 2024-05-26 13:16:00.798196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55d481cd682c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_table(
        "resource",
        sa.Column("name", sa.String(length=70), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("download_uri", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "TEXT",
                "WORD",
                "PDF",
                "IMAGE",
                "VIDEO",
                "AUDIO",
                "FOLDER",
                "UNKNOWN",
                name="mediatype",
            ),
            nullable=False,
        ),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column(
            "shared_access",
            sa.Enum(
                "PRIVATE", "ALL_READ", "ALL_COMMENT", "ALL_EDIT", name="sharedaccess"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "user_accesses",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("parent_resource_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("byte_size > 0", name="check_byte_size_is_positive_number"),
        sa.ForeignKeyConstraint(
            ["parent_resource_id"], ["resource.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("download_uri"),
    )
    op.create_table(
        "cart_resource",
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["cart.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resource.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cart_id", "resource_id", name="unique_cart_resource_ids"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_resource")
    op.drop_table("resource")
    op.drop_table("cart")
    op.execute("DROP TYPE mediatype, sharedaccess;")
    # ### end Alembic commands ###
