"""create updated_at trigger

Revision ID: e35ada8237da
Revises: b11f222ea820
Create Date: 2024-05-19 00:43:46.432042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e35ada8237da"
down_revision: Union[str, None] = "b11f222ea820"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """CREATE OR REPLACE FUNCTION set_updated_at()
            RETURNS TRIGGER 
            LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                NEW.updated_at := TIMEZONE('UTC', NOW());
                RETURN NEW;
            END;
            $$;"""
    )

    op.execute(
        """CREATE TRIGGER set_updated_at_trigger
			BEFORE UPDATE ON "resource"
			FOR EACH ROW
			EXECUTE FUNCTION set_updated_at();"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER set_updated_at_trigger ON "resource";""")
    # ### end Alembic commands ###
