"""create triggers

Revision ID: e4fed60fe0cc
Revises: 5c0a3a4a3a7c
Create Date: 2024-05-29 11:12:31.287641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4fed60fe0cc"
down_revision: Union[str, None] = "5c0a3a4a3a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """CREATE OR REPLACE FUNCTION set_updated_at()
            RETURNS TRIGGER 
            LANGUAGE PLPGSQL
            AS
            $$
            BEGIN
                NEW.updated_at := TIMEZONE('UTC', NOW());
                RETURN NEW;
            END;
            $$;"""
    )

    op.execute(
        """CREATE TRIGGER set_updated_at_for_resource_trigger
			BEFORE UPDATE ON "resource"
			FOR EACH ROW
			EXECUTE FUNCTION set_updated_at();"""
    )

    op.execute(
        """CREATE TRIGGER set_updated_at_for_cart_trigger
			BEFORE UPDATE ON "cart"
			FOR EACH ROW
			EXECUTE FUNCTION set_updated_at();"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER set_updated_at_for_resource_trigger ON "resource";""")
    op.execute("""DROP TRIGGER set_updated_at_for_cart_trigger ON "cart";""")
    # ### end Alembic commands ###
