"""byte_size is optional

Revision ID: e95242fa5d84
Revises: fcae19968429
Create Date: 2024-05-26 20:38:15.464591

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e95242fa5d84"
down_revision: Union[str, None] = "fcae19968429"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "byte_size", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "byte_size", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
