version: '3.9'

services:
  postgres_master:
    image: postgres
    container_name: postgres_master
    restart: always
    volumes:
      - postgres_master:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5434:5432

volumes:
  postgres_master: