export const USER_REPOSITORY_PROVIDER = "USER_REPOSITORY"
export const TOKEN_REPOSITORY_PROVIDER = "TOKEN_REPOSITORY"
export const SESSION_REPOSITORY_PROVIDER = "SESSION_REPOSITORY"
export const REDIS_CLIENT_PROVIDER = "REDIS_CLIENT"
